# Generated by Django 2.1 on 2018-11-29 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_app', '0002_auto_20181129_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='followers',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='following',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
