# Generated by Django 2.1.3 on 2018-12-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20181129_1214'),
        ('first_app', '0003_auto_20181202_0814'),
    ]

    operations = [
    ]
