# Generated by Django 2.1 on 2018-12-04 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_merge_20181203_1622'),
        ('first_app', '0004_merge_20181204_0833'),
    ]

    operations = [
    ]
