# Generated by Django 2.1 on 2018-12-04 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_merge_20181204_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='users',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
